### ISSUE TITLE
changing docker ports still show 9944/tcp, 30333/tcp and 30343/tcp on "docker ps"

### ISSUE THREAD

**Issue by powerpsy** [Cardinal-Cryptography/aleph-node-runner#64]
Hi, 
I changed all ports in the env/validator_testnet file

```
PORT=32333
VALIDATOR_PORT=32343
RPC_PORT=39944
METRICS_PORT=39615
```

When the container is launched using run_node.sh, I get this:

```
CONTAINER ID  a1569de4d2e2   
IMAGE         public.ecr.aws/p6e8q1z1/aleph-node:r-13.0
COMMAND       "./docker_entrypoint…"
CREATED       5 days ago
STATUS        Up 5 days
PORTS         9944/tcp, 30333/tcp, 0.0.0.0:32333->32333/tcp, :::32333->32333/tcp, 127.0.0.1:39615->39615/tcp, 30343/tcp, 0.0.0.0:32343->32343/tcp, :::32343->32343/tcp, 127.0.0.1:39944->39944/tcp
NAMES
```

There are still 9944/tcp, 30333/tcp, 30343/tcp which remain unchanged, is that normal ?
The node validate though so it must not be a blocking issue.

**Comment by piotrMocz** [comment]
Hey @powerpsy , thank you for reporting, let me look into it

**Comment by piotrMocz** [comment]
Hi @powerpsy! These unchanged ports you're seeing are a result of the `EXPOSE` command in the [aleph-node dockerfile](https://github.com/Cardinal-Cryptography/aleph-node/blob/main/docker/Dockerfile#L8) and they shouldn't cause any problems. I'll take the liberty of closing this issue if that's okay
